# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

commands:
  build-site:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore clojure dependency cache
          keys:
            - v1-dependencies-clj-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-clj-
      - restore_cache:
          name: Restore node dependency cache
          keys:
            - v1-dependencies-node-{{ checksum "yarn.lock" }}
            - v1-dependencies-node-

      # install dependencies
      - run:
          name: Build
          command: |
            yarn deps
            yarn release

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-clj-{{ checksum "deps.edn" }}

      - save_cache:
          paths:
            - ~/.cache/yarn
            - ~/repo/node_modules
          key: v1-dependencies-node-{{ checksum "yarn.lock" }}

jobs:
  stage:
    docker:
      - image: circleci/clojure:tools-deps-node
    steps:
      - build-site
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=public
  deploy:
    docker:
      - image: circleci/clojure:tools-deps-node
    steps:
      - build-site
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public

workflows:
  build-and-deploy:
    jobs:
      - stage:
          filters:
            branches:
              ignore: main
      - deploy:
          filters:
            branches:
              only: main
